compile:
	npx hardhat compile
	npx hardhat run scripts/compile.ts
test:
	npx hardhat test
run-node:
	npx hardhat node
deploy:
	npx hardhat run scripts/deploy.ts --network localhost
goerli:
	npx hardhat run scripts/deploy.ts --network goerli
scroll:
	npx hardhat run scripts/deploy.ts --network scroll
hardhat:
	npx hardhat node
link-balancer:
	npm link @balancer-labs/v2-pool-stable @balancer-labs/v2-interfaces @balancer-labs/v2-solidity-utils @balancer-labs/v2-pool-utils @balancer-labs/v2-helpers
